spring:
  datasource:
    url: jdbc:mysql://localhost:3306/database-desafio
    username: root
    password: Pablo#3008
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        format_sql: true